### PR TITLE
Fix set invalid input with invalid zipcode

### LINKED ISSUE #64: Zipcode validation doesn't mark field as invalid
The zipcode field is not marked as invalid when an invalid zipcode is input. So it is possible to submit the form with an invalid field.

In the GIF below, I enter an invalid zipcode and click the next field, but the zipcode field is marked as invalid only after I click it again and out. The zipcode service returns a 404 when fetching the address data.

cep_validation

### PR DESCRIPTION
**Pull request by williamcosta**
**CHANGELOG** :memo:

* Remove parameter not used
* Fix zipcodeInvalid verification to invalidated input, this resolve #64 

**PRINTS** :framed_picture:

### CODE REVIEW

File: src/components/Zipcode.js [hunk 1]
```diff
@@ -114,10 +114,14 @@ export default class Zipcode extends Component {
...
   onZipcodeError() {
-    const { value, zipcodeInvalid } = this.state;
+    const { value } = this.state;
     this.setState({ fullAddress: '', fetching: false, zipcodeInvalid: true });
 
-    this.props.onFieldBlur({ ...this.props, fetchCompleted: false, value: zipcodeInvalid ? '' : value });
+    this.props.onFieldBlur({
+      ...this.props,
+      fetchCompleted: false,
+      value: this.state.zipcodeInvalid ? '' : value,
```
Comment (dtamai) [inline src/components/Zipcode.js]: Is it possible that after setting the state with `zipcodeInvalid: true` on line 118, the state here is not invalid anymore? If so we could drop the conditional.

Comment (williamcosta) [reply src/components/Zipcode.js]: Thinking that this method is only called when an error happens, would give yes to eliminate the condition and always leave as the value being empty.

Comment (williamcosta) [reply src/components/Zipcode.js]: I removed the condition and now pass the empty value as default when there is error.
